// Strings and components shared by several pages.

import { site } from "../config.mjs";
import { disciplines } from "./content.mjs";
import { html, md, t } from "./html.mjs";
import { pagePath } from "./routes.mjs";

export const ui = {
  en: {
    skip: "Skip to content",
    nav: { expertise: "Expertise", team: "Team", about: "About", work: "Work", contact: "Contact" },
    navLabel: "Main",
    home: "Home",
    talk: "Talk to us",
    meetCrew: "Meet the crew",
    otherLanguage: "Nederlandse versie",
    logoLabel: "Bigger Boat, home",
    footerTagline:
      "A network of senior independent developers from the Netherlands. You work, and contract, directly with the people doing the work.",
    footerCta: ["Difficult project?", "Good.", "We like those."],
    footerPages: "Pages",
    footerContact: "Contact",
    footerLanguage: "Language",
    privacy: "Privacy",
    breadcrumbs: "Breadcrumbs",
    years: (n) => `${n}+ years of experience`,
    viewProfile: (name) => `${name}'s profile`,
    stats: {
      label: "Bigger Boat in numbers",
      members: "Senior developers",
      combined: "Years of combined experience",
      average: "Years of experience on average",
      disciplines: "Disciplines in one network",
      accountManagers: "Account managers required",
    },
    cta: {
      title: ["Need a bigger boat?", "Let's talk."],
      text: "You don't need a complete brief. Tell us what you're trying to build, or what's currently broken.",
      email: "Email",
      crew: "Or pick someone from the crew",
    },
    contract: {
      title: "How the collective works",
      text: "Bigger Boat brings the right people together. You work and contract directly with the independent professionals involved, without a traditional agency sitting in between.",
    },
  },
  nl: {
    skip: "Naar de inhoud",
    nav: { expertise: "Expertise", team: "Team", about: "Over ons", work: "Werk", contact: "Contact" },
    navLabel: "Hoofdmenu",
    home: "Home",
    talk: "Even sparren?",
    meetCrew: "Maak kennis met de crew",
    otherLanguage: "English version",
    logoLabel: "Bigger Boat, home",
    footerTagline:
      "Een netwerk van senior zelfstandige developers uit Nederland. Je werkt, en contracteert, rechtstreeks met de mensen die het werk doen.",
    footerCta: ["Lastig project?", "Mooi.", "Daar houden we van."],
    footerPages: "Pagina's",
    footerContact: "Contact",
    footerLanguage: "Taal",
    privacy: "Privacy",
    breadcrumbs: "Kruimelpad",
    years: (n) => `${n}+ jaar ervaring`,
    viewProfile: (name) => `Profiel van ${name}`,
    stats: {
      label: "Bigger Boat in cijfers",
      members: "Senior developers",
      combined: "Jaar gezamenlijke ervaring",
      average: "Jaar gemiddelde ervaring",
      disciplines: "Disciplines in één netwerk",
      accountManagers: "Accountmanagers nodig",
    },
    cta: {
      title: ["Bigger Boat nodig?", "Even sparren."],
      text: "Je hoeft nog geen compleet plan te hebben. Vertel wat je wilt bouwen, of wat er nu misgaat.",
      email: "Mail",
      crew: "Of kies zelf iemand uit de crew",
    },
    contract: {
      title: "Zo werkt het collectief",
      text: "Bigger Boat brengt de juiste mensen bij elkaar. Je werkt en contracteert rechtstreeks met de zelfstandige professionals die het werk uitvoeren, zonder traditioneel bureau ertussen.",
    },
  },
};

export const initials = (name) =>
  name
    .split(/\s+/)
    .filter((part) => /^[A-ZÀ-Ý]/.test(part))
    .map((part) => part[0])
    .filter((_, i, all) => i === 0 || i === all.length - 1)
    .join("");

// Photos are generated by `npm run images` into /images/team/{slug}-{width}.{format}.
export const photo = (member, { sizes = "(min-width: 48rem) 20rem, 100vw", eager = false } = {}) => {
  if (!member.photo) {
    return html`<div class="avatar" aria-hidden="true"><span>${initials(member.name)}</span></div>`;
  }
  const srcset = (format) => [320, 640].map((width) => `/images/team/${member.slug}-${width}.${format} ${width}w`).join(", ");
  return html`<picture class="avatar">
    <source type="image/avif" srcset="${srcset("avif")}" sizes="${sizes}">
    <source type="image/webp" srcset="${srcset("webp")}" sizes="${sizes}">
    <img src="/images/team/${member.slug}-640.jpg" width="640" height="800" alt="${member.name}" ${eager ? "fetchpriority=high" : html`loading="lazy"`} decoding="async">
  </picture>`;
};

export const tags = (items, className = "tags") =>
  items.length ? html`<ul class="${className}">${items.map((item) => html`<li>${item}</li>`)}</ul>` : "";

export const memberTags = (member, limit = 4) => [...member.technologies, ...member.expertise].slice(0, limit);

export const memberCard = (member, lang, { heading = "h3" } = {}) => html`<article class="member-card">
    ${photo(member, { sizes: "(min-width: 64rem) 16rem, (min-width: 40rem) 45vw, 90vw" })}
    <div class="member-card__body">
      ${html([`<${heading} class="member-card__name">`])}<a href="${pagePath("member", lang, member.slug)}" data-event="Team profile">${member.name}</a>${html([`</${heading}>`])}
      <p class="member-card__role">${t(member.role, lang)}</p>
      <p class="member-card__bio">${t(member.shortBio, lang)}</p>
      ${member.experience ? html`<p class="member-card__meta">${ui[lang].years(member.experience)}</p>` : ""}
      ${tags(memberTags(member))}
    </div>
  </article>`;

export const statsBar = (stats, lang) => {
  const s = ui[lang].stats;
  const items = [{ value: stats.members, label: s.members }];
  if (stats.combinedExperience) {
    items.push({ value: `${stats.combinedExperience}+`, label: s.combined });
    items.push({ value: stats.averageExperience, label: s.average });
  } else {
    items.push({ value: stats.disciplines, label: s.disciplines });
  }
  items.push({ value: 0, label: s.accountManagers });

  return html`<dl class="stats" aria-label="${s.label}">
    ${items.map((item) => html`<div class="stats__item"><dt>${item.label}</dt><dd>${item.value}</dd></div>`)}
  </dl>`;
};

export const emailLink = (lang, className = "button button--primary") =>
  html`<a class="${className}" href="mailto:${site.email}" data-event="Email click">${ui[lang].cta.email} ${site.email}</a>`;

export const ctaBlock = (lang) => {
  const c = ui[lang].cta;
  return html`<section class="cta" aria-labelledby="cta-title">
    <div class="container cta__inner">
      <h2 id="cta-title" class="cta__title">${c.title[0]} <span>${c.title[1]}</span></h2>
      <div class="cta__body">
        <p>${c.text}</p>
        <div class="actions">
          ${emailLink(lang)}
          <a class="button button--ghost" href="${pagePath("team", lang)}" data-event="CTA: team">${c.crew}</a>
        </div>
      </div>
    </div>
  </section>`;
};

export const contractNote = (lang) =>
  html`<aside class="note"><h2 class="note__title">${ui[lang].contract.title}</h2><p>${ui[lang].contract.text}</p></aside>`;

export const disciplineLabel = (key, lang) => t(disciplines[key], lang);

export const paragraphs = (items, lang) => (t(items, lang) ?? []).map((text) => html`<p>${md(text)}</p>`);

export const breadcrumbNav = (crumbs, lang) =>
  html`<nav class="breadcrumbs" aria-label="${ui[lang].breadcrumbs}"><ol>${crumbs.map((crumb, i) =>
    i === crumbs.length - 1
      ? html`<li><span aria-current="page">${crumb.name}</span></li>`
      : html`<li><a href="${crumb.path}">${crumb.name}</a></li>`,
  )}</ol></nav>`;
